title: Hamster party cam
hero_image: images/banner.png
description: Find out what your hamsters are up to during the night!
original_url: https://www.raspberrypi.org/learning/hamster-party-cam/
theme: navy
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-2, phys-comp-3, manufacture-1, community-0
interests: animals, photography
technologies: python, raspberry-pi, pi-camera
hardware: raspberry-pi, pi-camera
software: python
site_areas: projects
version: 4
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Hardware setup
- title: Recording video of the hamster
- title: Time-stamping the video
- title: Get the party started with lights
- title: Hamsters need music to dance
- title: "Challenge: build a better disco"
