title: Hamster Party Cam
hero_image: images/banner.png
description: Find out what your hamsters are up to during the night
original_url: https://www.raspberrypi.org/learning/hamster-party-cam/
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-1, programming-2, phys-comp-2, manufacture-0, community-0
interests: "pets, photography"
technologies: "python, raspberry pi, picamera"
steps:
  - title: Introduction
  - title: What you will need
  - title: Hardware setup
  - title: Recording video of the hamster
  - title: Time stamping the video
  - title: Get the party started with lights
  - title: Hamsters need music to dance
  - title: "Challenge: Build a better disco"

